### ISSUE TITLE
Cancellation of addition of a new user is not possible until 'role' is set

### ISSUE THREAD

**Issue by hansspanjers** [boxingbeetle/softfab#33] opened 2020-05-13 12:27 UTC
The cancellation of the addition of a new user is not possible until a 'role' is set. 

BTW: I'm wondering why 'guest' is not the default. That solves this problem too and can save one user action.

**Comment by hansspanjers** [comment] 2020-05-13 12:33
I noticed this problem on my Windows 10 system using Chrome. I got the message in an unfamiliar way. See screenshot. 
![image](https://user-images.githubusercontent.com/45046735/81812595-a6536300-9526-11ea-997c-689abef900e2.png)

**Comment by hansspanjers** [comment] 2020-05-13 14:20
Closed by accident.

**Comment by mthuurne** [comment] 2020-05-13 14:27
Probably the problem is that the role field is marked as mandatory and the "Cancel" button technically submits the form, which is then blocked by the browser because mandatory fields are empty.

Possible solution: don't have a "(not set)" option, but select a role (probably "user") by default.

**Closed** 2020-05-15 11:24 UTC
Labels: bug
